apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}-staging
  namespace: openshift-gitops
spec:
  project: ${{ values.name }}
  source:
    repoURL: https://${{ values.gitHost }}/${{ values.repoOwner }}/${{ values.repoName }}-gitops.git
    targetRevision: main
    path: kustomize/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.name }}-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
