apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ${{ values.name }}-approval
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.name }}
      app.kubernetes.io/component: approval
